### ISSUE TITLE
May I ask the author, can the shape-aware module be combined with SAN?

### ISSUE THREAD

**Issue by X-leaners** [Kebii/R2ET#5]

**Comment by Kebii** [comment]
SAN focuses on motion retargeting between skeletons with different topologies. Thus, the joint number of the skeleton used in SAN may be different from that of R2ET. The shape-aware module can be embedded into SAN after some modification of the skeleton topology, and the module also needs to be retrained.

**Comment by X-leaners** [comment]
Thank you!

**Comment by dddyyyplus** [comment]
> Thank you!

@X-leaners hello您好，我最近也在尝试做这个，请问可以和您交流讨论一下嘛😊
